server:
  port: 9090


spring:
  application:
    name: hmdp
  datasource:
    url: jdbc:mysql://${ip}:3306/UsstCafeteriaHub?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: klein

  session:
    timeout: 86400  # 1 day
#  data:
#    redis:
#      port: 6379
#      password: klein
#      lettuce:
#        pool:
#          max-active: 10
#          max-idle: 10
#          min-idle: 1
#          time-between-eviction-runs: 10s
    jackson:
      default-property-inclusion: non_null # JSON?????????



mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.usst.usstcafeteriahub.model.entity



logging:
  level:
    com.usst: debug
  pattern:
    dateformat: HH:mm:ss


ip: localhost

